[package]
name = "rode_sql_parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.1"
lazy_static = "1.4.0"
log = "0.4.20"
